### GET acheter
POST  http://localhost:4000/produit/acheter
Accept: application/json
Content-Type: application/json

{
    "ids":["64770c51ae29b7b3dbddd7a8","64770ccdae29b7b3dbddd7ab","647739c2e74b267baaee91e6"]
}

### POST ajouter
POST http://localhost:4000/produit/ajouter
Accept: application/json
Content-Type: application/json

{
   "nom": "pro 6",
    "description": "blabla bla",
    "prix": 10
}


### POST ajouter
POST http://localhost:4001/commande/ajouter
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InFAYS5jb20iLCJub20iOiJwcm8gNSIsImlhdCI6MTY4NTUzMTM4NH0.q0u4dfvPiwtpSAR9DQ6z_y83SnqoqevqNaqPPj_Q_8c

{
    "ids":["64770c51ae29b7b3dbddd7a8","64770ccdae29b7b3dbddd7ab","647710b7ff64179a11e412f3"],
   "email_utilisateur": "bllq@nll.com"
}

### GET acheter
GET  http://localhost:4001/commandes
Accept: application/json

### POST register
POST http://localhost:4002/auth/register
Accept: application/json
Content-Type: application/json

{
   "nom": "pro 5",
    "email": "q@a.com",
    "mot_passe": "wqwdrwerf"
}

### POST login
POST http://localhost:4002/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "q@a.com",
    "mot_passe": "wqwdrwerf"
}