### GET acheter
POST  http://localhost:4000/produits/acheter
Accept: application/json
Content-Type: application/json

{
    "ids":["64825322fc8bb05afdbf3c5a"]
}

### POST ajouter
POST http://localhost:4000/produits/ajouter
Accept: application/json
Content-Type: application/json

{
   "nom": "pro 1",
    "description": "jobino bla",
    "prix": 122
}


### POST ajouter
POST http://localhost:4001/commandes/ajouter
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InFAYS5jb20iLCJub20iOiJwcm8gNSIsImlhdCI6MTY4NjI2NTc0MH0.QC1sL16P0jvXQKUfO1VtltR1xNkxr8DcOSbEmn-pOeM

{
    "ids":["64825322fc8bb05afdbf3c5a"],
   "email_utilisateur": "q@a.com"
}

### GET acheter
GET  http://localhost:4001/commandes
Accept: application/json

### POST register
POST http://localhost:4002/auth/register
Accept: application/json
Content-Type: application/json

{
   "nom": "pro 5",
    "email": "q@a.com",
    "mot_passe": "wqwdrwerf"
}

### POST login
POST http://localhost:4002/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "q@a.com",
    "mot_passe": "wqwdrwerf"
}