version: "3"

services:
  command-app:
    build:
      context: .
    container_name: my-command
    depends_on:
      - db
    ports:
      - "4001:4001"
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - DB_NAME=command-service-db
      - SERVER_PORT=4001
      - JWT_KEY=bqbqbqbqbq


  db:
    image: mongo:latest
    container_name: command-db
    ports:
      - "27019:27017"